const DB_KEY='barzinhoPiscinaDB_v1';
const emptyDb=()=>({products:[],sales:[],movements:[]});
let db=loadDb();let cart=[];
function loadDb(){try{return JSON.parse(localStorage.getItem(DB_KEY))||emptyDb()}catch{return emptyDb()}}
function saveDb(){localStorage.setItem(DB_KEY,JSON.stringify(db))}
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const uid=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
const el=id=>document.getElementById(id);
function toast(msg){el('toast').textContent=msg;el('toast').classList.add('show');setTimeout(()=>el('toast').classList.remove('show'),2200)}
function seed(){if(db.products.length&&!confirm('Já existem produtos. Deseja adicionar os exemplos mesmo assim?'))return;const ex=[['Cerveja Lata','Bebidas',7,4.1,60,10,true],['Refrigerante Lata','Bebidas',6,3.2,40,8,true],['Água Mineral','Bebidas',4,1.4,50,10,true],['Porção de Batata','Porções',28,12,20,5,true],['X-Burguer','Lanches',18,8.5,25,5,true],['Espetinho','Porções',10,4.2,30,6,true]];db.products.push(...ex.map(x=>({id:uid('p'),name:x[0],category:x[1],price:x[2],cost:x[3],stock:x[4],minStock:x[5],trackStock:x[6]})));saveDb();renderAll();toast('Produtos de exemplo adicionados.')}
function setView(view){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));el(`view-${view}`).classList.add('active-view');const map={pdv:['PDV','Venda rápida no balcão e emissão de fichas.'],produtos:['Produtos','Cadastro de produtos, custos e preços.'],estoque:['Estoque','Acompanhe quantidade e valor parado.'],financeiro:['Financeiro','Faturamento, custos, lucro e movimentações.'],historico:['Histórico','Consulte vendas já concluídas.']};el('viewTitle').textContent=map[view][0];el('viewSubtitle').textContent=map[view][1];renderAll()}
function renderCategories(){const cats=[...new Set(db.products.map(p=>p.category))].sort();const cur=el('categoryFilter').value;el('categoryFilter').innerHTML='<option value="">Todas as categorias</option>'+cats.map(c=>`<option>${c}</option>`).join('');el('categoryFilter').value=cur}
function renderProductsForSale(){const term=el('searchProduct').value.toLowerCase(),cat=el('categoryFilter').value;const products=db.products.filter(p=>(!term||p.name.toLowerCase().includes(term))&&(!cat||p.category===cat));el('productGrid').innerHTML=products.length?products.map(p=>`<article class="product-card"><span class="category">${p.category}</span><h3>${p.name}</h3><div class="price">${money(p.price)}</div><div class="stock">${p.trackStock?`Estoque: ${p.stock}`:'Sem controle de estoque'}</div><button class="primary" data-add="${p.id}" ${p.trackStock&&p.stock<=0?'disabled':''}>Adicionar</button></article>`).join(''):'<div class="empty">Nenhum produto encontrado.</div>'}
function addToCart(id){const p=db.products.find(x=>x.id===id);if(!p)return;const row=cart.find(x=>x.productId===id),next=(row?.qty||0)+1;if(p.trackStock&&next>p.stock){toast('Quantidade maior que o estoque disponível.');return}if(row)row.qty++;else cart.push({productId:id,qty:1});renderCart()}
function changeQty(id,delta){const row=cart.find(x=>x.productId===id);if(!row)return;const p=db.products.find(x=>x.id===id),n=row.qty+delta;if(n<=0)cart=cart.filter(x=>x.productId!==id);else if(!p.trackStock||n<=p.stock)row.qty=n;renderCart()}
function renderCart(){el('cartItems').innerHTML=cart.length?cart.map(i=>{const p=db.products.find(x=>x.id===i.productId);return `<div class="cart-row"><div><strong>${p.name}</strong><span>${money(p.price)} × ${i.qty}</span></div><div class="qty-actions"><button data-minus="${p.id}">−</button><span>${i.qty}</span><button data-plus="${p.id}">+</button></div></div>`}).join(''):'<div class="empty">Adicione itens ao pedido.</div>';const total=cart.reduce((s,i)=>{const p=db.products.find(x=>x.id===i.productId);return s+p.price*i.qty},0);el('cartTotal').textContent=money(total)}
function finishSale(){if(!cart.length){toast('Adicione pelo menos um item.');return}const items=cart.map(i=>{const p=db.products.find(x=>x.id===i.productId);return{productId:p.id,name:p.name,qty:i.qty,unitPrice:p.price,unitCost:p.cost}});for(const i of items){const p=db.products.find(x=>x.id===i.productId);if(p.trackStock&&p.stock<i.qty){toast(`Estoque insuficiente para ${p.name}.`);return}}const sale={id:uid('v'),createdAt:new Date().toISOString(),mode:el('saleMode').value,payment:el('paymentMethod').value,items,total:items.reduce((s,i)=>s+i.unitPrice*i.qty,0),cost:items.reduce((s,i)=>s+i.unitCost*i.qty,0)};items.forEach(i=>{const p=db.products.find(x=>x.id===i.productId);if(p.trackStock)p.stock-=i.qty});db.sales.unshift(sale);saveDb();printSale(sale);cart=[];renderAll();toast('Venda concluída.')}
function printSale(sale){const tokens=sale.mode==='fichas'?sale.items.flatMap(i=>Array.from({length:i.qty},()=>`<div class="token"><strong>FICHA</strong><br>${i.name}</div>`)).join(''):'';el('printArea').innerHTML=`<div class="ticket"><h2>BARZINHO DA PISCINA</h2><p>Praça de Esportes</p><div class="line"></div><p>${new Date(sale.createdAt).toLocaleString('pt-BR')}</p>${sale.items.map(i=>`<div class="item"><span>${i.qty}x ${i.name}</span><strong>${money(i.unitPrice*i.qty)}</strong></div>`).join('')}<div class="line"></div><div class="item"><strong>TOTAL</strong><strong>${money(sale.total)}</strong></div><p>${sale.payment}</p>${tokens}</div>`;window.print()}
function renderProductTable(){el('productsTableWrap').innerHTML=db.products.length?`<table><thead><tr><th>Produto</th><th>Categoria</th><th>Venda</th><th>Custo</th><th>Estoque</th><th>Margem</th><th></th></tr></thead><tbody>${db.products.map(p=>`<tr><td>${p.name}</td><td>${p.category}</td><td>${money(p.price)}</td><td>${money(p.cost)}</td><td>${p.trackStock?p.stock:'—'}</td><td>${p.price>0?(((p.price-p.cost)/p.price)*100).toFixed(1)+'%':'0%'}</td><td><button class="link-btn" data-edit="${p.id}">Editar</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum produto cadastrado.</div>'}
function renderStock(){el('stockItems').textContent=db.products.length;el('stockCost').textContent=money(db.products.reduce((s,p)=>s+(p.trackStock?p.stock*p.cost:0),0));el('stockRevenue').textContent=money(db.products.reduce((s,p)=>s+(p.trackStock?p.stock*p.price:0),0));el('lowStock').textContent=db.products.filter(p=>p.trackStock&&p.stock<=p.minStock).length;el('stockTableWrap').innerHTML=db.products.length?`<table><thead><tr><th>Produto</th><th>Estoque</th><th>Mínimo</th><th>Situação</th><th>Custo unit.</th><th>Valor em estoque</th></tr></thead><tbody>${db.products.map(p=>`<tr><td>${p.name}</td><td>${p.trackStock?p.stock:'—'}</td><td>${p.trackStock?p.minStock:'—'}</td><td>${p.trackStock?(p.stock<=p.minStock?'<span class="badge low">Baixo</span>':'<span class="badge">OK</span>'):'Sem controle'}</td><td>${money(p.cost)}</td><td>${money(p.trackStock?p.stock*p.cost:0)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum produto cadastrado.</div>'}
function renderFinancial(){const rev=db.sales.reduce((s,v)=>s+v.total,0),cogs=db.sales.reduce((s,v)=>s+v.cost,0),profit=rev-cogs;el('revenue').textContent=money(rev);el('cogs').textContent=money(cogs);el('grossProfit').textContent=money(profit);el('margin').textContent=rev?`${(profit/rev*100).toFixed(1)}%`:'0%';const pay={};db.sales.forEach(v=>pay[v.payment]=(pay[v.payment]||0)+v.total);el('paymentSummary').innerHTML=Object.keys(pay).length?Object.entries(pay).map(([k,v])=>`<div class="movement"><span>${k}</span><strong>${money(v)}</strong></div>`).join(''):'<div class="empty">Sem vendas ainda.</div>';el('movementList').innerHTML=db.movements.length?db.movements.map(m=>`<div class="movement ${m.type}"><div><strong>${m.desc}</strong><small>${new Date(m.createdAt).toLocaleString('pt-BR')}</small></div><strong>${m.type==='saida'?'- ':'+ '}${money(m.value)}</strong></div>`).join(''):'<div class="empty">Nenhuma movimentação manual.</div>'}
function renderSales(){el('salesTableWrap').innerHTML=db.sales.length?`<table><thead><tr><th>Data</th><th>Itens</th><th>Tipo</th><th>Pagamento</th><th>Total</th><th>Lucro bruto</th></tr></thead><tbody>${db.sales.map(v=>`<tr><td>${new Date(v.createdAt).toLocaleString('pt-BR')}</td><td>${v.items.reduce((s,i)=>s+i.qty,0)}</td><td>${v.mode==='fichas'?'Fichas':'Imediato'}</td><td>${v.payment}</td><td>${money(v.total)}</td><td>${money(v.total-v.cost)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhuma venda concluída.</div>'}
function openProduct(id=null){const p=id?db.products.find(x=>x.id===id):null;el('productDialogTitle').textContent=p?'Editar produto':'Novo produto';el('productId').value=p?.id||'';el('productName').value=p?.name||'';el('productCategory').value=p?.category||'';el('productPrice').value=p?.price??'';el('productCost').value=p?.cost??'';el('productStock').value=p?.stock??0;el('productMinStock').value=p?.minStock??5;el('productTrackStock').checked=p?.trackStock??true;el('productDialog').showModal()}
function saveProduct(e){e.preventDefault();const id=el('productId').value;const data={name:el('productName').value.trim(),category:el('productCategory').value.trim(),price:+el('productPrice').value,cost:+el('productCost').value,stock:+el('productStock').value,minStock:+el('productMinStock').value,trackStock:el('productTrackStock').checked};if(id)Object.assign(db.products.find(x=>x.id===id),data);else db.products.push({id:uid('p'),...data});saveDb();el('productDialog').close();renderAll();toast('Produto salvo.')}
function addMovement(){const value=+el('movementValue').value,desc=el('movementDesc').value.trim();if(!value||!desc){toast('Informe descrição e valor.');return}db.movements.unshift({id:uid('m'),type:el('movementType').value,desc,value,createdAt:new Date().toISOString()});saveDb();el('movementDesc').value='';el('movementValue').value='';renderFinancial();toast('Movimentação registrada.')}
function renderAll(){renderCategories();renderProductsForSale();renderCart();renderProductTable();renderStock();renderFinancial();renderSales()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)setView(b.dataset.view);if(b.dataset.add)addToCart(b.dataset.add);if(b.dataset.plus)addToCart(b.dataset.plus);if(b.dataset.minus)changeQty(b.dataset.minus,-1);if(b.dataset.edit)openProduct(b.dataset.edit)});
el('searchProduct').addEventListener('input',renderProductsForSale);el('categoryFilter').addEventListener('change',renderProductsForSale);el('clearCart').addEventListener('click',()=>{cart=[];renderCart()});el('finishSale').addEventListener('click',finishSale);el('newProductBtn').addEventListener('click',()=>openProduct());el('productForm').addEventListener('submit',saveProduct);el('addMovement').addEventListener('click',addMovement);el('seedBtn').addEventListener('click',seed);setInterval(()=>el('clock').textContent=new Date().toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}),1000);renderAll();