const DB_KEY='barzinhoPiscinaDB_v1';
const emptyDb=()=>({products:[],sales:[],movements:[],purchases:[],stockAdjustments:[]});
let db=loadDb();let cart=[];let purchaseDraft=[];
function loadDb(){try{const data=JSON.parse(localStorage.getItem(DB_KEY))||emptyDb();data.products||=[];data.sales||=[];data.movements||=[];data.purchases||=[];data.stockAdjustments||=[];return data}catch{return emptyDb()}}
function saveDb(){localStorage.setItem(DB_KEY,JSON.stringify(db))}
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const uid=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
const el=id=>document.getElementById(id);
function toast(msg){el('toast').textContent=msg;el('toast').classList.add('show');setTimeout(()=>el('toast').classList.remove('show'),2200)}
function seed(){if(db.products.length&&!confirm('Já existem produtos. Deseja adicionar os exemplos mesmo assim?'))return;const ex=[['Cerveja Lata','Bebidas',7,4.1,60,10,true],['Refrigerante Lata','Bebidas',6,3.2,40,8,true],['Água Mineral','Bebidas',4,1.4,50,10,true],['Porção de Batata','Porções',28,12,20,5,true],['X-Burguer','Lanches',18,8.5,25,5,true],['Espetinho','Porções',10,4.2,30,6,true]];db.products.push(...ex.map(x=>({id:uid('p'),name:x[0],category:x[1],price:x[2],cost:x[3],stock:x[4],minStock:x[5],trackStock:x[6]})));saveDb();renderAll();toast('Produtos de exemplo adicionados.')}
function setView(view){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));el(`view-${view}`).classList.add('active-view');const map={pdv:['PDV','Venda rápida no balcão e emissão de fichas individuais.'],produtos:['Produtos','Cadastro de produtos, custos e preços.'],estoque:['Estoque','Ajuste quantidades e acompanhe valor parado.'],financeiro:['Financeiro','Vendas, compras de estoque, custos, entradas e saídas.'],historico:['Histórico','Consulte vendas, entregas e fichas emitidas.']};el('viewTitle').textContent=map[view][0];el('viewSubtitle').textContent=map[view][1];renderAll()}
function renderCategories(){const cats=[...new Set(db.products.map(p=>p.category))].sort();const cur=el('categoryFilter').value;el('categoryFilter').innerHTML='<option value="">Todas as categorias</option>'+cats.map(c=>`<option>${c}</option>`).join('');el('categoryFilter').value=cur}
function renderProductsForSale(){const term=el('searchProduct').value.toLowerCase(),cat=el('categoryFilter').value;const products=db.products.filter(p=>(!term||p.name.toLowerCase().includes(term))&&(!cat||p.category===cat));el('productGrid').innerHTML=products.length?products.map(p=>`<article class="product-card"><span class="category">${p.category}</span><h3>${p.name}</h3><div class="price">${money(p.price)}</div><div class="stock">${p.trackStock?`Estoque: ${p.stock}`:'Sem controle de estoque'}</div><div class="product-actions"><button class="secondary small" data-add-now="${p.id}" ${p.trackStock&&p.stock<=0?'disabled':''}>Entregar agora</button><button class="primary small" data-add-token="${p.id}" ${p.trackStock&&p.stock<=0?'disabled':''}>+ Ficha</button></div></article>`).join(''):`<div class="empty"><strong>${db.products.length?'Nenhum item combina com a busca.':'Seu balcão está pronto.'}</strong><br><span>${db.products.length?'Tente outro nome ou categoria.':'Cadastre os produtos ou use “Carregar exemplo” para ver o PDV funcionando.'}</span></div>`}
function getCartRow(id){return cart.find(x=>x.productId===id)}
function totalQty(row){return (row.immediateQty||0)+(row.tokenQty||0)}
function addToCart(id,kind){const p=db.products.find(x=>x.id===id);if(!p)return;let row=getCartRow(id);const next=(row?totalQty(row):0)+1;if(p.trackStock&&next>p.stock){toast('Quantidade maior que o estoque disponível.');return}if(!row){row={productId:id,immediateQty:0,tokenQty:0};cart.push(row)}if(kind==='token')row.tokenQty++;else row.immediateQty++;renderCart()}
function changeCart(id,kind,delta){const row=getCartRow(id);if(!row)return;const p=db.products.find(x=>x.id===id);const key=kind==='token'?'tokenQty':'immediateQty';const n=(row[key]||0)+delta;if(n<0)return;if(delta>0&&p.trackStock&&totalQty(row)+1>p.stock){toast('Quantidade maior que o estoque disponível.');return}row[key]=n;if(totalQty(row)<=0)cart=cart.filter(x=>x.productId!==id);renderCart()}
function renderCart(){el('cartItems').innerHTML=cart.length?cart.map(i=>{const p=db.products.find(x=>x.id===i.productId);return `<div class="cart-row detailed"><div class="cart-product"><strong>${p.name}</strong><span>${money(p.price)} por unidade</span></div><div class="cart-kind"><span>Agora</span><div class="qty-actions"><button data-dec-now="${p.id}">−</button><b>${i.immediateQty||0}</b><button data-inc-now="${p.id}">+</button></div></div><div class="cart-kind token-kind"><span>Fichas</span><div class="qty-actions"><button data-dec-token="${p.id}">−</button><b>${i.tokenQty||0}</b><button data-inc-token="${p.id}">+</button></div></div></div>`}).join(''):'<div class="empty"><strong>Nenhum item ainda.</strong><br><span>Escolha “Entregar agora” ou “+ Ficha” em cada produto.</span></div>';const total=cart.reduce((s,i)=>{const p=db.products.find(x=>x.id===i.productId);return s+p.price*totalQty(i)},0);const tokens=cart.reduce((s,i)=>s+(i.tokenQty||0),0);el('cartTotal').textContent=money(total);el('cartSubtotal').textContent=money(total);el('tokenCount').textContent=tokens}
function normalizedSaleItem(i){return{...i,immediateQty:i.immediateQty??i.qty??0,tokenQty:i.tokenQty??0,qty:(i.immediateQty??i.qty??0)+(i.tokenQty??0)}}
function finishSale(){if(!cart.length){toast('Adicione pelo menos um item.');return}const items=cart.map(i=>{const p=db.products.find(x=>x.id===i.productId);return{productId:p.id,name:p.name,immediateQty:i.immediateQty||0,tokenQty:i.tokenQty||0,qty:totalQty(i),unitPrice:p.price,unitCost:p.cost}});for(const i of items){const p=db.products.find(x=>x.id===i.productId);if(p.trackStock&&p.stock<i.qty){toast(`Estoque insuficiente para ${p.name}.`);return}}const sale={id:uid('v'),number:String(Date.now()).slice(-6),createdAt:new Date().toISOString(),payment:el('paymentMethod').value,items,total:items.reduce((s,i)=>s+i.unitPrice*i.qty,0),cost:items.reduce((s,i)=>s+i.unitCost*i.qty,0),tokenCount:items.reduce((s,i)=>s+i.tokenQty,0),immediateCount:items.reduce((s,i)=>s+i.immediateQty,0)};items.forEach(i=>{const p=db.products.find(x=>x.id===i.productId);if(p.trackStock)p.stock-=i.qty});db.sales.unshift(sale);saveDb();printSale(sale);cart=[];renderAll();toast('Venda concluída.')}
function printSale(sale){const tokenBlocks=sale.items.flatMap(item=>Array.from({length:item.tokenQty||0},(_,idx)=>`<section class="token-slip"><div class="tear">✂ DESTACAR AQUI</div><div class="token-brand">BARZINHO DA PISCINA</div><div class="token-order">Pedido #${sale.number}</div><div class="token-name">${item.name}</div><div class="token-seq">FICHA ${idx+1} DE ${item.tokenQty}</div><div class="token-valid">Entregue esta ficha no balcão para retirar 1 unidade.</div></section>`)).join('');el('printArea').innerHTML=`<div class="ticket"><section class="sale-receipt"><h2>BARZINHO DA PISCINA</h2><p>Praça de Esportes</p><p>Pedido #${sale.number}</p><div class="line"></div><p>${new Date(sale.createdAt).toLocaleString('pt-BR')}</p>${sale.items.map(i=>`<div class="item"><span>${i.qty}x ${i.name}</span><strong>${money(i.unitPrice*i.qty)}</strong></div>${i.immediateQty?`<div class="item sub"><span>↳ retirar agora</span><span>${i.immediateQty}</span></div>`:''}${i.tokenQty?`<div class="item sub"><span>↳ em fichas</span><span>${i.tokenQty}</span></div>`:''}`).join('')}<div class="line"></div><div class="item"><strong>TOTAL</strong><strong>${money(sale.total)}</strong></div><p>${sale.payment}</p></section>${tokenBlocks}</div>`;window.print()}
function renderProductTable(){el('productsTableWrap').innerHTML=db.products.length?`<table><thead><tr><th>Produto</th><th>Categoria</th><th>Venda</th><th>Custo</th><th>Estoque</th><th>Margem</th><th></th></tr></thead><tbody>${db.products.map(p=>`<tr><td>${p.name}</td><td>${p.category}</td><td>${money(p.price)}</td><td>${money(p.cost)}</td><td>${p.trackStock?p.stock:'—'}</td><td>${p.price>0?(((p.price-p.cost)/p.price)*100).toFixed(1)+'%':'0%'}</td><td><button class="link-btn" data-edit="${p.id}">Editar</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum produto cadastrado.</div>'}
function renderStock(){el('stockItems').textContent=db.products.length;el('stockCost').textContent=money(db.products.reduce((s,p)=>s+(p.trackStock?p.stock*p.cost:0),0));el('stockRevenue').textContent=money(db.products.reduce((s,p)=>s+(p.trackStock?p.stock*p.price:0),0));el('lowStock').textContent=db.products.filter(p=>p.trackStock&&p.stock<=p.minStock).length;el('stockTableWrap').innerHTML=db.products.length?`<table><thead><tr><th>Produto</th><th>Estoque</th><th>Mínimo</th><th>Situação</th><th>Custo unit.</th><th>Valor em estoque</th><th>Ações</th></tr></thead><tbody>${db.products.map(p=>`<tr><td>${p.name}</td><td>${p.trackStock?p.stock:'—'}</td><td>${p.trackStock?p.minStock:'—'}</td><td>${p.trackStock?(p.stock<=p.minStock?'<span class="badge low">Baixo</span>':'<span class="badge">OK</span>'):'Sem controle'}</td><td>${money(p.cost)}</td><td>${money(p.trackStock?p.stock*p.cost:0)}</td><td class="actions-cell"><button class="link-btn" data-stock="${p.id}" ${!p.trackStock?'disabled':''}>Ajustar estoque</button><button class="link-btn" data-edit="${p.id}">Editar produto</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum produto cadastrado.</div>'}
function renderFinancial(){const rev=db.sales.reduce((s,v)=>s+Number(v.total||0),0),cogs=db.sales.reduce((s,v)=>s+Number(v.cost||0),0),profit=rev-cogs,purchases=db.purchases.reduce((s,p)=>s+Number(p.total||0),0);el('revenue').textContent=money(rev);el('cogs').textContent=money(cogs);el('purchasesTotal').textContent=money(purchases);el('grossProfit').textContent=money(profit);el('margin').textContent=rev?`${(profit/rev*100).toFixed(1)}%`:'0%';const pay={};db.sales.forEach(v=>pay[v.payment]=(pay[v.payment]||0)+v.total);el('paymentSummary').innerHTML=Object.keys(pay).length?Object.entries(pay).map(([k,v])=>`<div class="movement"><span>${k}</span><strong>${money(v)}</strong></div>`).join(''):'<div class="empty compact">Sem vendas ainda.</div>';el('movementList').innerHTML=db.movements.length?db.movements.slice(0,12).map(m=>`<div class="movement ${m.type}"><div><strong>${m.desc}</strong><small>${new Date(m.createdAt).toLocaleString('pt-BR')}</small></div><strong>${m.type==='saida'?'- ':'+ '}${money(m.value)}</strong></div>`).join(''):'<div class="empty compact">Nenhuma movimentação.</div>';renderPurchases()}
function renderPurchases(){el('purchasesTableWrap').innerHTML=db.purchases.length?`<table><thead><tr><th>Data</th><th>Fornecedor</th><th>Produtos comprados</th><th>Pagamento</th><th>Total</th></tr></thead><tbody>${db.purchases.map(p=>`<tr><td>${new Date(p.createdAt).toLocaleString('pt-BR')}</td><td>${p.supplier||'Não informado'}</td><td>${p.items.map(i=>`${i.qty}x ${i.name} (${money(i.unitCost)})`).join('<br>')}</td><td>${p.payment}</td><td><strong>${money(p.total)}</strong></td></tr>`).join('')}</tbody></table>`:'<div class="empty compact">Nenhuma compra registrada. Use “Registrar compra” para dar entrada nos produtos e lançar a saída financeira.</div>'}
function renderSales(){el('salesTableWrap').innerHTML=db.sales.length?`<table><thead><tr><th>Data</th><th>Itens</th><th>Entregues agora</th><th>Fichas</th><th>Pagamento</th><th>Total</th><th>Lucro bruto</th></tr></thead><tbody>${db.sales.map(v=>{const items=(v.items||[]).map(normalizedSaleItem);const totalItems=items.reduce((s,i)=>s+i.qty,0),now=items.reduce((s,i)=>s+i.immediateQty,0),tokens=items.reduce((s,i)=>s+i.tokenQty,0);return `<tr><td>${new Date(v.createdAt).toLocaleString('pt-BR')}</td><td>${totalItems}</td><td>${now}</td><td>${tokens}</td><td>${v.payment}</td><td>${money(v.total)}</td><td>${money(v.total-v.cost)}</td></tr>`}).join('')}</tbody></table>`:'<div class="empty">Nenhuma venda concluída.</div>'}
function openProduct(id=null){const p=id?db.products.find(x=>x.id===id):null;el('productDialogTitle').textContent=p?'Editar produto':'Novo produto';el('productId').value=p?.id||'';el('productName').value=p?.name||'';el('productCategory').value=p?.category||'';el('productPrice').value=p?.price??'';el('productCost').value=p?.cost??'';el('productStock').value=p?.stock??0;el('productMinStock').value=p?.minStock??5;el('productTrackStock').checked=p?.trackStock??true;el('productDialog').showModal()}
function saveProduct(e){e.preventDefault();const id=el('productId').value;const data={name:el('productName').value.trim(),category:el('productCategory').value.trim(),price:+el('productPrice').value,cost:+el('productCost').value,stock:+el('productStock').value,minStock:+el('productMinStock').value,trackStock:el('productTrackStock').checked};if(id)Object.assign(db.products.find(x=>x.id===id),data);else db.products.push({id:uid('p'),...data});saveDb();el('productDialog').close();renderAll();toast('Produto salvo.')}
function openStock(id){const p=db.products.find(x=>x.id===id);if(!p)return;el('stockProductId').value=id;el('stockProductName').textContent=p.name;el('stockCurrent').value=p.stock;el('stockNew').value=p.stock;el('stockReason').value='';el('stockDialog').showModal()}
function saveStockAdjustment(e){e.preventDefault();const p=db.products.find(x=>x.id===el('stockProductId').value);if(!p)return;const oldStock=Number(p.stock||0),newStock=Number(el('stockNew').value),reason=el('stockReason').value.trim();if(newStock<0||!reason){toast('Informe o novo estoque e o motivo.');return}p.stock=newStock;db.stockAdjustments.unshift({id:uid('a'),productId:p.id,productName:p.name,oldStock,newStock,difference:newStock-oldStock,reason,createdAt:new Date().toISOString()});saveDb();el('stockDialog').close();renderAll();toast('Estoque ajustado e histórico registrado.')}
function openPurchase(){purchaseDraft=[];el('purchaseSupplier').value='';el('purchaseQty').value='';el('purchaseUnitCost').value='';renderPurchaseProductOptions();renderPurchaseDraft();el('purchaseDialog').showModal()}
function renderPurchaseProductOptions(){el('purchaseProduct').innerHTML=db.products.length?db.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join(''):'<option value="">Cadastre um produto primeiro</option>'}
function addPurchaseDraftItem(){const id=el('purchaseProduct').value,p=db.products.find(x=>x.id===id),qty=Number(el('purchaseQty').value),unitCost=Number(el('purchaseUnitCost').value);if(!p||qty<=0||unitCost<0){toast('Informe produto, quantidade e custo unitário.');return}const existing=purchaseDraft.find(x=>x.productId===id&&x.unitCost===unitCost);if(existing)existing.qty+=qty;else purchaseDraft.push({productId:id,name:p.name,qty,unitCost});el('purchaseQty').value='';el('purchaseUnitCost').value='';renderPurchaseDraft()}
function renderPurchaseDraft(){const total=purchaseDraft.reduce((s,i)=>s+i.qty*i.unitCost,0);el('purchaseItems').innerHTML=purchaseDraft.length?purchaseDraft.map((i,idx)=>`<div class="purchase-item"><div><strong>${i.qty}x ${i.name}</strong><span>${money(i.unitCost)} cada</span></div><div><strong>${money(i.qty*i.unitCost)}</strong><button type="button" class="link-btn" data-remove-purchase="${idx}">Remover</button></div></div>`).join(''):'<div class="empty compact">Adicione os produtos comprados.</div>';el('purchaseTotalPreview').textContent=money(total)}
function savePurchase(e){e.preventDefault();if(!purchaseDraft.length){toast('Adicione pelo menos um produto à compra.');return}const purchase={id:uid('c'),createdAt:new Date().toISOString(),supplier:el('purchaseSupplier').value.trim(),payment:el('purchasePayment').value,items:purchaseDraft.map(i=>({...i})),total:purchaseDraft.reduce((s,i)=>s+i.qty*i.unitCost,0)};purchase.items.forEach(i=>{const p=db.products.find(x=>x.id===i.productId);if(!p)return;const oldStock=Number(p.stock||0),oldCost=Number(p.cost||0),newStock=oldStock+i.qty;p.cost=newStock>0?((oldStock*oldCost)+(i.qty*i.unitCost))/newStock:i.unitCost;p.stock=newStock});db.purchases.unshift(purchase);db.movements.unshift({id:uid('m'),type:'saida',source:'purchase',refId:purchase.id,desc:`Compra de estoque${purchase.supplier?` · ${purchase.supplier}`:''}`,value:purchase.total,createdAt:purchase.createdAt});saveDb();purchaseDraft=[];el('purchaseDialog').close();renderAll();toast('Compra registrada, estoque atualizado e saída lançada.')}
function addMovement(){const value=+el('movementValue').value,desc=el('movementDesc').value.trim();if(!value||!desc){toast('Informe descrição e valor.');return}db.movements.unshift({id:uid('m'),type:el('movementType').value,desc,value,createdAt:new Date().toISOString(),source:'manual'});saveDb();el('movementDesc').value='';el('movementValue').value='';renderFinancial();toast('Movimentação registrada.')}
function renderAll(){renderCategories();renderProductsForSale();renderCart();renderProductTable();renderStock();renderFinancial();renderSales()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)setView(b.dataset.view);if(b.dataset.addNow)addToCart(b.dataset.addNow,'now');if(b.dataset.addToken)addToCart(b.dataset.addToken,'token');if(b.dataset.incNow)changeCart(b.dataset.incNow,'now',1);if(b.dataset.decNow)changeCart(b.dataset.decNow,'now',-1);if(b.dataset.incToken)changeCart(b.dataset.incToken,'token',1);if(b.dataset.decToken)changeCart(b.dataset.decToken,'token',-1);if(b.dataset.edit)openProduct(b.dataset.edit);if(b.dataset.stock)openStock(b.dataset.stock);if(b.dataset.removePurchase!==undefined){purchaseDraft.splice(Number(b.dataset.removePurchase),1);renderPurchaseDraft()}});
el('searchProduct').addEventListener('input',renderProductsForSale);el('categoryFilter').addEventListener('change',renderProductsForSale);el('clearCart').addEventListener('click',()=>{cart=[];renderCart()});el('finishSale').addEventListener('click',finishSale);el('newProductBtn').addEventListener('click',()=>openProduct());el('productForm').addEventListener('submit',saveProduct);el('stockForm').addEventListener('submit',saveStockAdjustment);el('newPurchaseBtn').addEventListener('click',openPurchase);el('addPurchaseItem').addEventListener('click',addPurchaseDraftItem);el('purchaseForm').addEventListener('submit',savePurchase);el('addMovement').addEventListener('click',addMovement);el('seedBtn').addEventListener('click',seed);setInterval(()=>el('clock').textContent=new Date().toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}),1000);renderAll();